### ISSUE TITLE
Support ${workspaceFolder} in perforce.command setting

### ISSUE THREAD

**Issue by jfg118** [mjcrouch/vscode-perforce#153]
I would like to avoid placing a hard coded path to the p4 executable in the setting and would like to be able to resolve the p4.command to a location relative to the workspaceFolder.

Example:

p4.command = "${workspaceFolder}/bin/p4"

This would allow the workspace to be compatible across multiple sites where the path to p4 varies and can be handled by a p4 command within the workspace.

**Comment by mjcrouch** [comment]
Thanks - it probably would be possible to do this for specific values like workspace folder - 
unfortunately there's no API to automatically do this for us currently.

Ideally, we would have https://github.com/microsoft/vscode/issues/46471 / https://github.com/microsoft/vscode/issues/2809 (they seem to overlap) to help do the substition since there are a whole range of different variables

We could still manually work it out by looking for that variable and substituting with the workspace path - would need to think about how it would work in some edge cases like
* not having a workspace folder open (since you can still open files from perforce) - presumably that just wouldn't work
* multi-root workspaces. If you had multiple folders open, we would probably want to pick the workspace folder of the file that we are operating on - as opposed to the root level workspace folder

**Comment by scp096** [comment]
Hi, @mjcrouch. My enviornment is RemoteSSH. I would like add a proxy on p4. Is there any method that I can place "proxychains4 p4" in p4.command?

**Comment by mjcrouch** [comment]
@scp096 - this is not really related to this issue - please raise a new issue if the below doesn't work:

I haven't tried wrapping p4. You could try changing the `perforce.command` setting to include the wrapper, but I don't think that would work because it treats it as a single shell argument

You could try defining an alias in your environment, e.g. in your shell scripts that run on login, `alias p4proxy=proxychains p4`

then in vscode set `perforce.command` to `p4proxy`. I think it would respect aliases but I haven't tried it.

**Comment by jfg118** [comment]
@scp096 depending on your platform you could write a simple helper script to handle the chaining of the p4 commands.  i.e. You could have a #!/bin/bash script which does an SSH and executes the p4 command on the remote machine.  Just pass through the arguments properly quoted. 

```
#!/bin/bash
quote_args()  {
  store=
  while [ $# -gt 0 ]; do
    ## printf %q requires bash (-vs- /bin/sh)
    store=$store${store:+ }`printf %q "$1"`
    shift
  done
  echo "$store"
  unset store
}
exec ssh hostName $(quote_args "$@")

```

**Comment by jfg118** [comment]
@mjcrouch it is unfortunate that VSCode does not have an API available to perform the substitution.  At a minimum having ${workspaceFolder} would be helpful.  For multi-root workspaces there looks to be the ${workspaceFolder:name} type of syntax to get to a specific workspaceFolder.  [https://code.visualstudio.com/docs/editor/variables-reference](variables-reference)  

From a general perspective I could see how the platform may come into play as well, since this setting may vary between platforms.  I see a few issues where people are trying to customize the Python executable setting.  Some settings / extensions seem to support having a platform setting based on "windows", "mac, "linux" with the appropriate setting.

**Comment by scp096** [comment]
Sry too late to give a feedback. 
@mjcrouch, Alias doesn't work here, it hints 
`Error: spawn p4proxy ENOENT`
 @jfg118, just to clarify, I develop using RemoteSSH extension in VSCode. Sciprt is a good try, I wrote a sciprt p4.sh in /usr/bin
`proxychains4 p4 $@`, 
VSCode can detect it, and run the cmd, the only problem is that SCM still stuck at "Looking for perforce client workspaces"
``

**Comment by mjcrouch** [comment]
@scp096  - you're right, the alias doesn't work

To test this I tried the same thing as you. I just wrapped p4 in a script p4.sh that ran `p4 $@` and for good measure, another script that ran `p4.sh $@` and set that one as my perforce command. (I haven't tried proxychains). This worked fine on my system. It could be an issue with how proxychains is run (no idea) or something else in your workspace.

What is shown in the perforce output log?

If you have an extremely large workspace with lots of folders, it can take a while to scan for p4config files - if so you could try turning off `perforce.enableP4ConfigScanOnStartup`
