### ISSUE TITLE
Plugin not working with versions 2017.2 & 2017.3

### ISSUE THREAD

**Issue by cmario92** [mjcrouch/vscode-perforce#166]
**Describe the bug:**
Having an older version(I tried with 2017.2 & 2017.3 versions) does not introduce a `p4.exe` in the Program Files/Perforce directory. This is causing the plugin not to work.

**Expected behavior:**
Should check also for `p4v.exe` instead of checking only for `p4.exe` as it does not exist in older version.

**To Reproduce:**
Mentioned above.

**Versions & Details:**
 - Perforce extension: 2017.2 & 2017.3
 - VSCode version: 1.47 Insiders @latest (as of June 12th, 2020)
 - Operating System: Windows 10
 - Perforce server details (if known): Behind a corp proxy
 - Are you using a multi-root workspace?: Yes - configured properly

**Additional context**

<details>

Managed to make it work, by upgrading to 2020.1 version of Perforce
</details>

**Comment by mjcrouch** [comment]
Hi,

Thanks for raising -

 > Should check also for p4v.exe instead of checking only for p4.exe as it does not exist in older version.

I'm not sure what you mean by this - p4v is the visual tool and isn't able to perform any of the commands needed by the extension

As per the readme the extension requires the p4 command line client - I have successfully used the extension with a version as early as 2014.1 without any significant issues. I suspect the issue was just that you only had p4v installed and not the command line client

**Comment by cmario92** [comment]
most probably this might be the issue yes, but if I am correct, there is no prompt to install the command line tools for Perforce 2017 during the x64 installation, whereas in the 2020 version, I got prompt if I want to install command line tools as well. 

Maybe is a separate installation for older versions?

**Comment by mjcrouch** [comment]
quite likely - the perforce website has a dedicated download page for the command line client - we only have a weird constrained app installer at my workplace to prevent installing random third party software, so for that old version I haven't used the standard installer.

I don't think there's much that can be done about this in the extension anyway - the requirement for the command line client is documented and the client is available - and the p4 installer has since been improved - so closing this issue :)

**Comment by cmario92** [comment]
no problem, now everything is clear! keep up the good work!

Thanks @mjcrouch
