### ISSUE TITLE
Path filters for pending changelists

### ISSUE THREAD

**Issue by scottbilas** [mjcrouch/vscode-perforce#173]
**Is your feature request related to a problem? Please describe.**

We have a monorepo with many projects in it, and I have a VS Code workspace for each of the projects I'm working on. I work on a few things at once, so I have many pending changelists for multiple unrelated projects.

The problem is that all of these show up mixed together in the "Source Control" view.

**Describe the solution you'd like**

If I had the "Files" filter from the Search Changelists panel in my main changelist panel, then this would completely solve it! I'd just add a filter or two for the paths of that workspace, easy. (I especially like how the Search Changelists file filter makes it easy to pick different predefined paths like workspace root.)

**Describe alternatives you've considered**

I thought about prefixing changelist descriptions with "[projectname]" so I can use the "Ignored Changelist Prefix" feature, but given it's opt-out rather than opt-in, this wouldn't scale to more than two projects.

If the prefix were a regex, or there was another one that was opt-in, it would be more manageable, but it would still require manually prefixing changelist descriptions. Folder-based filtering is simpler and automatic.

Another option I've considered is making a client per project, but none of my tooling/scripts is expecting this, plus we have some shared folders that would end up duplicated or otherwise more difficult to manage. I currently add the folders into each vscode project workspace, which is nice.

**Comment by mjcrouch** [comment]
Thanks, interesting!

To start - given you are using different VS code workspace for each one have you tried the "hide non workspace files" setting? Probably "hide changelists" or "hide changelists, hide files in default changelist" are the best options. It might be nice to have a quick way to set this from the scm context menu if you'd like to toggle it more often.

If that's not sufficient and you're actually opening the root of the mono repo then I could see some dynamic filtering might be useful:

So, we are a bit limited in what we can add to the scm view - the changelist search is a whole separate view so it is flexible, but the "source control" view itself is fixed in structure. If we want some dynamic filters, we could add a button to the context icons at the top of the view (where the current "sync" icon sits). This could then open up a quick pick / input like the filter one when clicked.

My only concern being it might not be obvious to a user that they've applied a filter previously. Depends on whether we persist them after closing / re-opening I guess. One way of doing it might be a bit hacky but we could add a dummy "changelist" that just says something like "Filters Applied" so that it's obvious that filtering is going on. Might have some wider implications doing that though...

p.s. Good to know that someone uses the search changelists as this is the first real feedback I've had on it :) (nobody on my team at work noticed its existence!)

**Comment by scottbilas** [comment]
Oh awesome, the "hide changelists" option exactly solves this for me. :)

I had reviewed this setting previously, but it was as part of a "let's look at all the Perforce settings!" so I was moving fast, and I think also the big WARNING led me astray. I thought it was talking about the entire feature, and it described behavior I definitely didn't want. I didn't realize it was referring to one specific choice ("hide non workspace files") out of the four options. The name of that choice also happens to be the name of the setting itself, which also contributed to my misread.

I'll take a wild guess that previously this was a bool that became an enum as the feature set expanded, but the setting holds onto its previous name for easier upgrade path at the time.

Maybe some wording changes could improve it for others like me in the future. I'm happy though, my issue is resolved. Thank you for your response!

**Comment by mjcrouch** [comment]
> I'll take a wild guess that previously this was a bool that became an enum

that's it - when I forked the extension it was a bool which just hides non-workspace files from all changelists, but it came with that problem, I think the warning was present in the text but worded slightly differently.

I personally wouldn't use the 'legacy' behaviour for it because it seems too risky to me for changelists to not show all of the files they contain, but I decided to keep it rather than break people who do want that behaviour.

Found it very difficult to describe all the behaviour in the config so it could probably be improved! Actually I think that's a generally hard thing about developing vs code extensions - I know when I install other extensions I'll rarely dig into the config at-all unless something isn't working, so it's hard to make people aware of all the options.
