### ISSUE TITLE
Cannot close a repository

### ISSUE THREAD

**Issue by hdpoliveira** [mjcrouch/vscode-perforce#174]
Both Git and Hg extensions allow closing an opened repository, but the Perforce extension doesn't.

![perforce close](https://user-images.githubusercontent.com/35645457/89668272-e28f2900-d8b3-11ea-9604-c222c1da9876.gif)

Please implement this capability. The only workaround now is to close all files and reload the window.

**Comment by mjcrouch** [comment]
Thanks, I hadn't seen that. Seems reasonable, we try to look at implementing when I have some time

Just for more details, as you mention closing files - is this a p4 client that's automatically been detected by opening some files outside of a vs code workspace? I'm just thinking about what the behaviour should be in that case if you choose to close the repo and then open another file that belongs to the same p4 client... (I can always experiment with Git and compare anyway, makes sense to match behaviour)

**Comment by hdpoliveira** [comment]
Yes, it was a perforce client detected upon opening files.

I noticed it closes the client automatically when closing the files as well, so I don't really need to reload the window (is this new? We recently got a request to implement this behavior in Hg extension https://github.com/mrcrowl/vscode-hg/issues/156)

The behavior for git and hg is that when you close the repo and open another file belonging to the repository it reopens the repository anyway. This is the safest approach but is sometimes annoying: you just told vscode that you don't want to see that, right?

Maybe a more usable approach would be to keep track of the repositories closed by the user and not reopen them unless explicitly told to, but then we'd need a way to explicit tell vscode to reopen a repository. One option is to have a "Open Source Control" option on the file context menu - this would be much better if it were an option supported by vscode itself to which we could hook to. A second option would be to provide a command via the pallet to reopen a closed repository.

**Comment by hdpoliveira** [comment]
Answering to your edit: my use case is that sometimes I open coworkers' files to review/suggest changes. So my use case in specific could be addressed by not opening clients my user is not allowed to interact to, but I'm not sure this is a good way to go because it may be useful to see the changes my coworkers are working on.

**Comment by mjcrouch** [comment]
> is this new?

It depends what you mean by new - I implemented this I think in v4.0.0 at the same time as auto detecting p4 clients when you open single files. The actual behaviour is implemented using a callback on `onDidCloseTextDocument` which is a little unpredictable, because the concept of a TextDocument *can* outlive the editor tab that you closed - I think there's an issue somewhere in vscode repo for a mechanism to track which tabs you have open.
(Note that you can disable both auto activation and deactivation of files, though probably not relevant to this issue)

I could possibly add a setting that, when enabled, keeps things closed until you restart.
If that were enabled, you could also have a command to clear the list of closed perforce clients. Though I think this is quite niche and most people would probably never notice its existance / understand what it means.

**Comment by hdpoliveira** [comment]
@mjcrouch  thanks very much for the fix and for the hints! I'll try to implement this behavior of closing repositories in vscode-hg.
