### ISSUE TITLE
Refresh Editor Window After Revert

### ISSUE THREAD

**Issue by a18rhodes** [mjcrouch/vscode-perforce#177]
After performing a revert on the currently opened file, the old changes are still shown even though the file has been reverted. Can this be changed so that after the revert happens, the current version is displayed (e.g., after revert, display the HEAD of the open file)?

**Comment by mjcrouch** [comment]
Hi, thanks for raising - I'm not quite sure exactly which parts you're referring to

Can you give a screenshot if possible or some steps with exactly where to look?

What kind of editor window - a normal editor or a diff editor?
By "the old changes" - do you mean the diffs that are shown in the gutter?

**Comment by a18rhodes** [comment]
I unfortunately can't post any screen shots due to company policy. 

To try and phrase differently, I have the "Perforce: Revert - Discard changes from the current file" command set up on my bindkey ctrl+r when editor is in focus. So when, for example, I have a file open in the editor window and have it opened for edit, then I make a few edits, but decide against it, I use ctrl+r to revert these changes. This all works fine, however, then the editor window still shows my code edits (on the now read-only file) that are not on disk. Now, if I switch to a new editor tab, then switch back to the one that I just reverted, the on-disk (e.g., HEAD) version of the file is displayed and my edits are gone as expected. Is there any way to get the editor to do the refresh for me instead of having to switch between editor tabs?

**Comment by mjcrouch** [comment]
Here's what it looks like for me - I can't see anything relating to the old change after reverting

![recording (2)](https://user-images.githubusercontent.com/49367953/89818149-36fb0880-db41-11ea-957a-940cc862940a.gif)

not sure why it behaves differently... The actual changes to revert the file should be done by perforce, and vs code should detect that the file has changed. There may be a setting in vs code I'm not aware of ignore external changes, or something about the filesystem you're using? I know sometimes I've had "unable to watch for file changes in this large workspace" when opening a workspace, which is fixed by changing some OS level setting that I forget

**Comment by a18rhodes** [comment]
Ah I see, yours does behave differently than mine. I can see the file gets reverted properly in Linux by opening with Vim but without changing editor tabs around, my VSCode view of the file doesn't update. I think you may be on to something about the "watch for changes" error. I get that every time I open up VSCode, and I assumed that files opened in the editor would be watched, where others would be ignored, but that must not be the case. Feel free to close out and I will find a way to get VSCode to watch my files.

Thanks!

**Comment by mjcrouch** [comment]
Seems likely to be the problem - in any case I don't think it's something we're really in control of in the extension, so will close :)
