### ISSUE TITLE
Using with tslint or eslint vscode plugins causes issues with imports

### ISSUE THREAD

**Issue by davestevens** [mjcrouch/vscode-perforce#188]
**Describe the bug:**
When using tslint or eslint plugins with vscode and using imports results in a list of errors around not being able to find modules.
This looks like it is due to it running on the temp files used for comparison (#have at the end of files)

**Expected behavior:**
Problems tab should not display errors for the temp file.

**To Reproduce:**

1. Setup tslint or eslint in vscode (including plugin)
2. Edit file which is in the perforce depot
3. Ensure that you are using `import`
4. View the `Problems` tab with in the vscode terminal

**Versions & Details:**
 - Perforce extension: 4.13.0
 - VSCode version: 1.49.2
 - Operating System: Windows 10
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: No

**Additional context**

There are exclude options for tslint and eslint however, as the file paths are outside of the directories (they are full path files) there doesn't seem to be anyway to ignore them. I've tried `"**/*#have"` and the full path as I see it but I can't seem to get rid of it. Not sure if this is something that has come up before, I could not see anything in the issues.

Although it does not show up in the editor while working on a file, the fact that the problems tab shows it can be confusing.

```
Please open view -> Output, select "Perforce Log" from the dropdown and paste it here, if possible / relevant
```

</details>

**Comment by mjcrouch** [comment]
thanks, not something I've seen before - I haven't tried using eslint or tslint in a perforce project.

I think the problem here is that vscode technically "opens" a virtual file for comparison.  In this case we have a `FileSystemProvider` that handles a scheme called `perforce:` (instead of `file:`) and provides the file contents back to vs code. This is similar to other SCM providers. Note that the "#have" part is not actually part of the file path. I think it's probably a formatted version of the Uri (we use both the "fragment" segment and the "authority" segment to encode the revision for formatting in different scenarios, so it will be coming from one of those. As far I can see ignores can only be applied to the "path" segment).

From the perspective of the linting extension, I think this is not much different from just opening a file normally in an editor window.

The following is mostly guesswork:

My suspicion is this is more related to those extensions rather than the perforce extension, and it'll probably depend on how you have those extensions set up. Because the protocol is different, I believe if it's looking for a `.eslintrc`, `.eslintignore` or similar, it should be looking using the `perforce:` scheme and not the `file:` scheme. So for example if you do have an eslintrc in your workspace, I'm not sure how it would be handled (e.g. would it find the equivalent one in the `perforce` world?)

I've been looking through the eslint extension config but can't see any obvious settings that would prevent it from picking up files with a different scheme - I think this may need to be raised as a question in their repo or in vscode as I don't know of any way I could prevent this from happening in the perforce extension.

**Comment by davestevens** [comment]
Thanks for getting back to quickly!
Yeah its a bit of a weird one, I wasn't sure whether it was this plugin or the tslint/eslint, as it was happening in both I figured I would ask here.

"#have" does show as part of the file path in the problems panel so I was assuming it using this as part of the linting options.
I'm going to have a dig around over the weekend.

**Comment by davestevens** [comment]
So, i've been digging a bit and found that its nothing to do with eslint or tslint, with neither of them enabled it still shows in the "Problems" section. It seems to be due to the file path having an extra slash as the start, e.g. `/d:/file.ts` rather than `d:/file.ts` so its breaking the import path which is causing the errors, which makes sense.

There is a filter option for "Show Active File Only" which removes the error from being seen, though this needs to be changed each time.

Its definitely not this plugin that is the problem, I suspect you were right about the file scheme which is causing it to be a problem. I have a temporary solution and a bit more of an idea about the problem now. Thanks for your input!

**Comment by retepaskab** [comment]
> Its definitely not this plugin that is the problem, I suspect you were right about the file scheme which is causing it to be a problem. I have a temporary solution and a bit more of an idea about the problem now. Thanks for your input!

Please share your workaround, this bugs me too.

**Comment by davestevens** [comment]
The temporary solution is simply to use the filter option, not great (and doesn't persist).
Hopefully i'll get some time to dig a bit deeper at some point.
