### ISSUE TITLE
Submit single files

### ISSUE THREAD

**Issue by a18rhodes** [mjcrouch/vscode-perforce#20]
Not an issue, but a suggestion would be to provide method to submit single files in the default changelist instead of the whole changelist. For example command line would be p4 submit -d "message" <file>.

**Comment by mjcrouch** [comment]
Thanks, I agree with the idea but how do you think the UI should work?

A couple of thoughts 
- Using the standard message box at the top of the SCM view allows line breaks but it's not very flexible and I can't think of a usable flow that involves that box.
- There is an existing "submit default changelist" command, which submits everything in the default changelist. This pops up a box asking for the changelist description, then asks you if you want to submit or save as a changelist. It doesn't allow line breaks in the description :(
- I've just added to master the option to multi-select files, choose  "move to changelist" and select "new changelist..." instead of one of the existing ones - it prompts for a description and creates the changelist which you could then submit. Perhaps that's good enough?

**Comment by a18rhodes** [comment]
I like the option that you have of being able to move files to alternate changelists.

I think one possible solution would be to have a SCM option/shortcut that is "submit - Submit an existing file", matching the edit - Open an existing file for edit option where it will submit the file that is currently opened in the editor.
