### ISSUE TITLE
Add Badge Support Similar to Git

### ISSUE THREAD

**Issue by a18rhodes** [mjcrouch/vscode-perforce#201]
Can support for badges be added similar to how Git allows badges? E.g., allow for adding badges next to the file name in browser and editor to show if the file is opened for edit.

**Comment by mjcrouch** [comment]
I was going to say no because I remember the API was not public for a long time - but it looks like the API was finally made public in 1.52 ( microsoft/vscode/#47502 ) - so yes it probably can be added!
I haven't done a lot of work on the extension lately as I'm not at the same company any more but I may try to have a look at doing this

**Comment by a18rhodes** [comment]
Fantastic! I haven't done much work on VSCode extensions, but I will also have a look and submit a pull request if I am able to get it working.

**Comment by mjcrouch** [comment]
Thanks - I'm a bit rusty on my own code now but if you do want to, looking at how I think the API works - it could probably hook in to scm/Model.ts somewhere around where we create the resource groups. Possibly look at the `_openResourcesByPath` collection

e.g. whenever we add or remove from the collection we can fire the `onDidChangeFileDecorations` event for the file's `underlyingURI` if it exists. Probably either `Model` or `ScmProvider` could implement the new interface itself since it needs to also `provideDecorations` for the URI - which means getting the open resource and checking the action etc. (see `ScmProvider.provideOriginalResource` for a similar thing).

Note that there can be multiple `ScmProvider`/`Model` instances at any one time if you have multiple perforce clients in view but I don't think that should matter much

**Comment by mjcrouch** [comment]
new release should be pusing now with this in - sorry if you had started working on it! figured you hadn't since you don't have a fork - I just had some free time and gave it a go

**Comment by a18rhodes** [comment]
Fantastic, thank you! No worries either I started to take a look but didn't have time to do any meaningful work on it.
