### ISSUE TITLE
Source control count badge in activity bar is wrong

### ISSUE THREAD

**Issue by a18rhodes** [mjcrouch/vscode-perforce#204]
**Describe the bug:**
It seems like after adding the file badges, the activity bar icon file count doesn't match the number of files that are actually opened. E.g., I have 11 files opened, and that is what I see when I am looking through the items in the source control pane; but the badge count on the source control icon says 26 (e.g., the icon on the far left under the explorer and search icons).

**Expected behavior:**
The count on the activity bar icon should match the number of files shown in the source control pane.

**To Reproduce:**
Can't confirm that it will reproduce, but my flow was to reconcile in Linux (`p4 reconcile /some/directory/...`) (I am using remote SSH), refresh the source control pane in VSCode on Windows, submit a bunch of files using VSCode, then the count on the icon doesn't decrement to match the number of files now opened.

**Versions & Details:**
 - Perforce extension: 4.15.0
 - VSCode version: 1.53.2
 - Operating System: Windows 10
 - Perforce server details (if known): Linux x86 install version 2018.2/1740258
 - Are you using a multi-root workspace?: Yes

**Additional context**

<details>

Perforce log probably can't be uploaded due to corporate policy.

</details>

**Comment by mjcrouch** [comment]
hmm, thanks - haven't been able to repro so far. The decorations *shouldn't* have any impact on the file count because they're just decorations and aren't explicitly tied to source control as far as the vs code API is concerned.

Could you check for any errors in the developer console? (Developer: Toggle developer tools). Also if you can reproduce it reliably & you have the chance, can you try installing the previous version and doing the same steps to make sure it's an actual change in behaviour?

**Comment by a18rhodes** [comment]
Sorry, should have tried restarting VSCode before raising the issue. It seems like after re-launching, all the counts match up as expected. After relaunching, I did a dummy p4 edit in linux, refreshed in VSCode, and then submitted from VSCode and the icon count matches the one in the pane, so it seems all is good after restarting.

**Comment by mjcrouch** [comment]
thanks - will close for now and re-open if we find a way to make it happen again!
