### ISSUE TITLE
Problems view shows errors for file with #have

### ISSUE THREAD

**Issue by wormszer** [mjcrouch/vscode-perforce#219]
**Describe the bug:**
Errors are listed in the problems view for a file with the #have while the same file without it does not have the same errors.

**Expected behavior:**
Errors for #have should not be shown

**Versions & Details:**
 - Perforce extension: v4.15.2
 - VSCode version: 1.60.2
 - Operating System: windows
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: No

**Additional context**

<details>

```
Please open view -> Output, select "Perforce Log" from the dropdown and paste it here, if possible / relevant
```

</details>
![image](https://user-images.githubusercontent.com/3580758/135293595-0c6db0a0-e54b-4be2-951f-07db9151f315.png)

**Comment by mjcrouch** [comment]
Hi, thanks for reporting - this seems to be a change in behaviour in vs code that has happened at some point - I just tried an import in TS on an older vs code version (from last year or earlier this year sometime) and there were no errors with the revision, then upgraded vs code to the latest version and it did include errors.

From a bit of searching it seems to match this issue in vscode: https://github.com/microsoft/vscode/issues/134271 which is marked as resolved last week so should be fixed in an upcoming release.
