### ISSUE TITLE
NO CLIENT ROOT FOUND in workspace root directory

### ISSUE THREAD

**Issue by yang-yuke** [mjcrouch/vscode-perforce#223]
Hi, Dear mjcrouch sir,

Is this extension applicable to Linux perforce? I am running vscode on a windows machine. I ssh to the remote Linux host in vscode code. I have installed the perforce extension in the remote host vscode. And I have also set the relevant parameters in vscode's settings.json file. Somehow, the perforce extension seems not taking effect. Could you please help take a look at the issue for me?

My settings.json file is as below:
![settings_json](https://user-images.githubusercontent.com/49341101/140456159-2e2163b4-fb47-467d-a993-213a6003f30e.png)

My client name and client root is as below:
![p4_info](https://user-images.githubusercontent.com/49341101/140456684-6c653299-be82-4f9e-a11b-4dc1efa6d45e.png)

Somehow, once I reload the vscode developer window, there will be below error message in the output of vscode. The error prompt says NO CLIENT ROOT FOUND in workspace root directory. But from the p4 info, there should be client root in the workspace root directory.
![output](https://user-images.githubusercontent.com/49341101/140457073-323bedd7-491b-4ad7-854b-6566ea42ea2d.png)

**Comment by mjcrouch** [comment]
Hi @yang-yuke - the problem here is the line "Error: spawn p4 ENOENT" which means that the shell used for running the commands (in vs code, I think this is called the automation shell) does not recognise p4 as a valid command.

This suggests that there is something setting up your p4 environment that runs on your normal login, but not in the automation shell. I don't know what though as it will depend a lot on your environment. Seems a bit similar to https://github.com/mjcrouch/vscode-perforce/issues/217

You could try setting the perforce.command setting to the full path to your p4 binary, which might work around the problem for your case.

**Comment by yang-yuke** [comment]
Hi Dear Mr mjcrouch,

Thank you for your prompt reply. I have checked the #217 thread you mentioned. My phenomenon is a bit similar to his. p4 command works when I type it separately on the terminal, but it fails in the automation sheel. I think it could help. In that thread, according to SilverGekko, he populates the p4.command field in the settings.json file a path to a script. 

But I don't know whether we have such a script, and where is the script also. Do you know what does this p4.command field mean? Should it be the location of the p4 installation? or its binary location? I don't know where would perforce be installed in Linux. Could you please give some examples of what this p4.command would normally be?

**Comment by mjcrouch** [comment]
If you look at the command it's running in the perforce output: `p4 -u 'yukeyang'...` then the `perforce.command` setting just changes the `p4` in that command to the value of perforce.command. Normally, just running p4 would work, but if your automation shell is not inheriting your normal environment then it might be missing from the path.

My suggestion would be:
- open a terminal where p4 works
- type `which p4`
- copy the path to p4 and put it into the `perforce.command` setting in vs code

This probably is not the best fix, but if you override all the settings and this works then it probably won't be too important.

**Comment by yang-yuke** [comment]
Thank you Mr mjcouch for your timely response!! Actually when I type the p4 edit command in the vscode terminal, it works. I can see the file will be checked out in perforce in Linux.
![image](https://user-images.githubusercontent.com/49341101/140756577-960d738a-2305-4e5a-a740-74f7ce100333.png)
![image](https://user-images.githubusercontent.com/49341101/140756769-c5704aba-fe96-489f-b870-a1fe8f25ef36.png)


And when I revert the file with p4 revert command in vscode terminal, it also works normally. So it seems it is normal using p4 command in vscode terminal.
![image](https://user-images.githubusercontent.com/49341101/140757134-65ccf918-13b2-4e70-a7df-3da35a6d68d3.png)
![image](https://user-images.githubusercontent.com/49341101/140757248-88f053a5-87b5-452b-825d-b896f67cae9f.png)

I try the method you recommend, it seems working normally now. You are such a brilliant genius! But I still have some doubts.

From below logging, it seems the p4 extension is now initialized normally right? I can see a message saying "Found workspace using root directory", unlike previous one. 
![image](https://user-images.githubusercontent.com/49341101/140757655-8c26629e-1ed4-463b-9aa3-a04243bf8dad.png)

It seems the setting in the settings.json file will override the setting in the .p4config file? I haven't type the password either in the settings.json file nor .p4config file, why does the p4 extension work? Also, if I disable these setting related to p4 in settings.json file and instead setting them in the .p4config file, would it still work?
![image](https://user-images.githubusercontent.com/49341101/140757937-a32b6ac5-065c-4cc9-86e9-f4ef1c3ad26f.png)
![image](https://user-images.githubusercontent.com/49341101/140758149-f4e6911c-90a3-4be2-a30e-c0ed9938feac.png)

Last but not least, after the p4 extension initialized, I see some messages saying "File(s) not opened on this client." Is it expected? Why is such?
![image](https://user-images.githubusercontent.com/49341101/140758882-dbc2dbb1-121c-4200-84b2-860c4b3664a6.png)
![image](https://user-images.githubusercontent.com/49341101/140759475-0bdca544-a4f4-4149-86df-54343410feab.png)

**Comment by mjcrouch** [comment]
> I haven't type the password either in the settings.json file nor .p4config file, why does the p4 extension work?

Most likely, you have already logged in from the same IP address so you have a valid ticket. Perforce login is by IP address (I think) so it doesn't matter which application you are using to run the commands, you only need to log in once per IP until the ticket expires.

> Also, if I disable these setting related to p4 in settings.json file and instead setting them in the .p4config file, would it still work?

In theory yes, that would be the better option, but I think it might fail because your automation shell does not have the same environment (e.g. p4 is missing from the path) so it's likely that your p4config settings would not be detected.  I'm not sure why this happens, and I'm fairly sure it's not specific to this extension. You can try it though. If it doesn't work you would probably need more general support from vs code community

> Last but not least, after the p4 extension initialized, I see some messages saying "File(s) not opened on this client." Is it expected? Why is such?

This is expected, whenever you open a file in the editor it checks the status to display it on the status bar at the bottom. If the file is not part of your client workspace then p4 prints this message.

**Comment by yang-yuke** [comment]
Thank you so much Mr mjcrouch! Now I am clear. I can use the perforce extension normally in vscode now. Such great integration, such a smooth experience!

**Comment by amorphobia** [comment]
Same issue here. My workaround is to create a shell script that wraps the real `p4` executable:

```csh
#!/usr/bin/csh
source /path/to/p4.cshrc
/path/to/p4 $argv:q
```

and set this script as `perforce.command`.

I guess the reason was that the automation shell used by perforce did not source my `.cshrc` and just call `p4` directly.
