### ISSUE TITLE
Integrate 3-Way Merge tool

### ISSUE THREAD

**Issue by a18rhodes** [mjcrouch/vscode-perforce#233]
The newest release seems to include a merge tool. Is there any way to get this to work with this extension?
https://code.visualstudio.com/updates/v1_69#_3-way-merge-editor

**Comment by mjcrouch** [comment]
It looks like intersting - I think from the release notes it's currently git specific and not exposed to the API, so probably not currently - but I haven't been keeping up with the features recently to see if there's any experimental API for it.

I did once have a look at inline merging (like the existing git merge where you see the commit markers in the file and choose which whether to keep the source etc) - IIRC the problem was that I couldn't find a reliable way to have the mergefile open in the editor - if you set the p4 editor to vs code then there were some conditions (I think it was OS dependent) where it wouldn't open the file correctly.
With git for example I think merging involves multiple commands - one command which triggers the merge, and writes the conflict markers etc. directly into the file, then further commands to commit the updated file or abort the merge. This is more intuitive since you keep the same file open in the editor.  However with perforce it's a single interactive command to do merging, and it writes the mergefile out somewhere else, which makes it more complicated to interact with. I do think it's possible to get the merge conflicts out, display some temporary file content in the editor and do the merging there but it would be more tricky!

**Comment by a18rhodes** [comment]
Ah very interesting. No problem then, it seems like Perforce really wants you to use its merge too.
