### ISSUE TITLE
Revert Fails for "Cannot read property 'model' of undefined"

### ISSUE THREAD

**Issue by a18rhodes** [mjcrouch/vscode-perforce#24]
**Describe the bug:**
When reverting file using Ctrl-Shft-P Perforce: Revert file no revert happens and an error dialog in the lower right pops up saying "Cannot read property 'model' of undefined". However, when using the source control tab, right click on file and revert file works fine.

**Expected behavior:**
File changes should be reverted in perforce -- same as running command line p4 revert <filename>

**To Reproduce:**
Happens every time I run the steps in the description

**Versions & Details:**
 - Perforce extension: 3.4.0
 - VSCode version: 1.41.1
 - Operating System: Linux x64
 - Perforce server details (if known): Unknown
 - Are you using a multi-root workspace?: Yes

**Additional context**

<details>

```
There is nothing even getting output here when running the command, when right clicking and clicking revert file, the expected output is dumped (e.g., p4 revert <file> etc.)
```

</details>

**Comment by mjcrouch** [comment]
I think the reason for this is that the command is designed for the context menu rather than the command palette.

Basically, when you add a command to any vscode extension, you put it into the extension's package.json. This makes it available for use in context menus, but it also automatically adds it to the command palette (ctrl+shift+p or f1).

I don't think it was ever intended to be run from the palette - none of the functions have been coded to handle it as it requires some extra work to handle the different inputs and get the currently opened file. You will probably get the same error for a lot of these commands.
(I confirmed this is the same on the slevesque version of the extension)

Alternative options to work around:
* Click the P4 icon in the status bar and choose revert
   * this is also accessible with the default keybinding of `alt+p space` (bleurgh) - you can rebind it in vscode by binding the `perforce.menuFunctions` command
* Use the source control tab (as you did!)

In terms of implementation - two options:
* Hide the commands from the command palette - I think this is possible
* Update all the functions to handle empty params, and if so, apply them to the currently opened editor
  * This isn't that difficult on a case by case basis but it would take a while to get through them all
   * (it's probably worth refactoring some of the functions down to something simpler as the code for all of these functions is quite repetitive)

**Comment by mjcrouch** [comment]
(just adding a comment as I edited the above - don't think the email notifications get sent for edits)
