### ISSUE TITLE
Make use of vs code 3-way merge

### ISSUE THREAD

**Issue by ulfwin** [mjcrouch/vscode-perforce#246]
It would be REALLY nice if this already great add-on would also support the new 3-way merge feature of vs code!
https://code.visualstudio.com/updates/v1_73#_merge-editor

The command line interface apparently has support for it, so maybe that could be used?
![image](https://user-images.githubusercontent.com/9116407/201872475-a27c5694-5816-4875-b765-b33c6fc0c213.png)

I know there is an option to provide the P4editor:
![image](https://user-images.githubusercontent.com/9116407/201873903-b3942bc7-e252-4bc1-bedb-de746f9bd55b.png)

But I guess the problem is that only one file is supplied, not three that could be absorbed by the merge tool. 

If there is any interest in implementing this, I'd be happy to try things out!

**Comment by mjcrouch** [comment]
Hi, thanks for raising, this was also requested in #233 but I didn't think it was possible to use the merge tool for anything other than git, but maybe it is (assuming that the command line screenshot is from vscode!) - if this is the case then there may also be a command you can execute directly in the extension to open a 3-way merge editor with the various paths instead of using the command line. (the same way we execute vscode.diff in the extension now to open a diff editor for a file)

> But I guess the problem is that only one file is supplied, not three that could be absorbed by the merge tool.

yes, I don't think we could give a vscode command to p4 and have it open the editor, because of the way p4 works I think we would have to
- run the p4 resolve interactively and interpret the output to decide what needs to be shown in the merge editor - we would probably need some UI (e.g. a quick pick for the user to make choices about merges) instead of allowing the user to interact with the command line directly, which is currently the only way resolving works in the extension
- possibly write some temp files for the merging (may not be necessary if the merge editor supports different schemas, we might be able to display some file directly from the perforce path),
- write the merged output back into perforce's mergefile and then continue the command in perforce

Certainly, I think it could be _possible_, but probably not easy - you're welcome to investigate further if you have some time - I don't think I would have much time to write this myself

**Comment by mjcrouch** [comment]
Having said that, there is a [P4MERGE](https://www.perforce.com/manuals/cmdref/Content/CmdRef/P4MERGE.html) environment variable that might make it possible to use a custom editor, suspect it would have the same problems with `--wait` as P4EDITOR does though.

**Comment by ulfwin** [comment]
Ah! Some good information in the P4MERGE link. I'll take a look and give it a try!

**Comment by ulfwin** [comment]
I got it to work with only P4MERGE! As suggested in the p4 documentation, I created a batch file (I'm on windows) to rearrange the arguments:
```
SET base=%1
SET theirs=%2
SET yours=%3
SET merge=%4
code --wait --merge %theirs% %yours% %base% %merge%
```

In the P4MERGE environment variable I'm simply pointing to the above script. `--wait` works as expected in this case.

Regarding the P4EDITOR, I also saw that it didn't work, but using P4DIFF does:
![image](https://user-images.githubusercontent.com/9116407/202390756-37efccf5-b986-44b8-8e13-509936869646.png)

Maybe that can be used as an override instead?

I should probably share that I sometimes see error messages, both for Merge and Diff, but they don't seem to affect anything:
```
Diff chunks: 0 yours + 0 theirs + 0 both + 1 conflicting
Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) e: d

[20748:1117/085821.826:ERROR:service_worker_storage.cc(1904)] Failed to delete the database: Database IO error
[13040:1117/090019.811:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) e: a
There are still change markers: confirm accept (y/n)? n
Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) e: d

[26172:1117/090155.387:ERROR:service_worker_storage.cc(1904)] Failed to delete the database: Database IO error
[11752:1117/090353.382:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
```

So perhaps an override for P4MERGE would be in place here? I'm happy changing it globally, but it follows naturally since P4EDITOR can be overrided I guess.

What would be really nice though, would be to avoid the separate batch file and include that functionality in the extension. Would that be difficult you think?

Thanks in advance!

**Comment by mjcrouch** [comment]
thanks for looking into it, good to know it can be done!

> What would be really nice though, would be to avoid the separate batch file and include that functionality in the extension. Would that be difficult you think?

I think it would be possible just to ship the batch file in the extension and have an option to override P4MERGE when running the resolve command. Would need to make sure it handles the various platforms and shell properly though which might be the hard bit - e.g. I think we would still need to run it through another command to re-order the arguments on linux and mac - exact method might be different for each

Obviously a fully integrated UI like I described in my earlier comment would be nicer than the command line but that would be significantly harder to implement!

**Comment by ulfwin** [comment]
True, a bit of a hassle to get it to work for both platforms. I'm ok with how it's currently setup, so I'll close this issue. Thanks for your answers!
