### ISSUE TITLE
Extension is generating URIs which are causing vscode-csharp to error in the diff view.

### ISSUE THREAD

**Issue by makzimus** [mjcrouch/vscode-perforce#260]
Please see the issue submitted for vscode-csharp [here](https://github.com/dotnet/vscode-csharp/issues/6256).

**Comment by mjcrouch** [comment]
thanks for reporting - it was quite a while ago but I seem to remember this being a rather hacky way to pass around the details we needed for the diff view & view of historic files in general (inspired by how gitlens worked at the time) - the information like @=1234 is really not an 'authority' but I recall there were some very annoying edge cases in vs code that made it impossible to pass the data in e.g. the query string where it would make more sense.

So, perhaps there have been improvements in the core vs code that make it possible to do it in a better way, or perhaps it would be simpler to just modify the encoding to meet the URL spec whithout changing where we put it.

**Comment by tru** [comment]
Any news on this? It makes it hard to use this plugin in my project since I want to have C# extension work as well. Is there a workaround at least?

**Comment by mjcrouch** [comment]
Hi - I think I have a working fix for the issue - the code for handling perforce URIs is quite complicated but the encoding of the revision in the authority of the URI is as far as I can recall now just for display purposes - it's only referenced in the extension config for the forrmatting of the editor title and otherwise ignored.

So I can replace "#" with text like "-rev-" and "=" with text like "shelved-" and everything generally still works, just the display of the title changes slightly when opening a single file from the depot.

Hopefully will have a new version soon with this fix
