### ISSUE TITLE
Perforce source control badge shows wrong number

### ISSUE THREAD

**Issue by davidavetyan** [mjcrouch/vscode-perforce#281]
Perforce SCM badge always shows the number of total files in the workspace (opened + shelved), no matter what setting is selected for `perforce.countBadge`. By default 'all-but-shelved' is selected, but the count of 'all' files is shown.

The issue started happening from VS Code version **1.91**. On **1.90.2** the count is shown correctly for the same workspace.

**Comment by mjcrouch** [comment]
Hi,

thanks for reporting. I think this is an issue in vscode - probably this https://github.com/microsoft/vscode/issues/221553

it looks like essentially vs code was accidentally ignoring the count we provide and falling back to using the number of items in the source control list. This should be fixed in the next vs code version.

**Comment by davidavetyan** [comment]
The issue is fixed in VS code 1.92 (tried with version **1.92.2**)
