### ISSUE TITLE
Make p4.annotate behave more like GitLens

### ISSUE THREAD

**Issue by ynain** [mjcrouch/vscode-perforce#33]
It would be useful if we could make the `p4.annotate` function behave more like the [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) extension for Git.

- Not opening a duplicate tab when using the function
- Be able to see changesets, users, comments, date/time in each line by hovering your mouse on the line
![Blame functionality](https://raw.githubusercontent.com/eamodio/vscode-gitlens/master/images/docs/current-line-blame.png)
- Searchable commits
- See recent commits

We could leverage this functionality by combining `p4 annotate`, `p4 filelog`, `p4 describe`, and a few others.

**Comment by mjcrouch** [comment]
Working on this one - here's how it looks so far, still quite a lot to work on

![Peek 2020-03-05 08-26](https://user-images.githubusercontent.com/49367953/75962197-38057b00-5ebb-11ea-85ce-06ff897e3ee1.gif)

* Doesn't show you the revision anywhere yet
* I'd like to add the option to follow branch actions (this means revision numbers become pretty meaningless, unless they also say where they came from)
* Need to add age indicator
* Would be good to add custom formatting to the gutter message so the user can choose what they want to see in there

It still opens in a new window, showing the current depot file. Making it open in the same window like GitLens is somewhat difficult because it means you also have to work out the diff from the depot file - and GitLens even shows you edit times for your file changes - Not sure how that is done yet. So ultimately I'll probably split that part out to a new issue

**Comment by mjcrouch** [comment]
Getting further on the annotation view - added everything I mentioned above except for putting the hover message on the code itself.  With a bit of code tidying and some testing it's *almost* in a publishable state.
Once it's published we can iterate on it more to add some extra features, like linking off to more details about a previous revision or changelist, seeing the other files edited at the same time, etc

![Peek 2020-03-11 21-56](https://user-images.githubusercontent.com/49367953/76468182-44219900-63e3-11ea-94f5-eef7a760995d.gif)
