### ISSUE TITLE
Tidy up multi-root workspaces

### ISSUE THREAD

**Issue by mjcrouch** [mjcrouch/vscode-perforce#41]
Currently, when multiple-roots are open, it creates one scm provider per workspace (if it finds a valid p4 client config for that workspace).

However, that may be the same client for two different workspaces, resulting in duplication of changes

see https://github.com/stef-levesque/vscode-perforce/issues/163

I think there may be other issues associated with the way the clients are set up, like https://github.com/stef-levesque/vscode-perforce/issues/176 which could probably be rolled up into this.

The concept of scm providers should be separated from workspaces. There should be one scm provider per perforce client - there may be multiple scm providers per workspace (e.g. if there are multiple .p4config files), or there may be multiple workspaces per scm provider, (e.g. if two workspaces use the same client)

We should easily be able to work out from a file Uri which scm provider instance it 'belongs' to. Probably, find the first scm provider whose client root is above the open file - this does not seem to be trivial with the current approach but would be if these changes were made.

Ultimately this may help to resolve the disparity between PerforceCommands and ScmProvider, where the same operations are defined in different places in two different ways. Instead, we could run all commands via the appropriate scm provider - though we need to be careful not to break any less common use cases!

The changes to detect conflicts between display / scm provider (made in #40) would be more simple if the scm provider was the thing checking the state in the first place (Edit: though perhaps, this doesn't work when editing files outside of the workspace - if .p4configs are used a default p4 command could work in those files - while an scm provider won't be found)

More thoughts:
- What if perforce client configuration item doesn't match a .p4config file in the workspace, but both are valid - should we only have one or the other?
- Similarly, a valid .p4config inside a valid client - we should probably preference the most specific
- What if we have two workspaces that are located under the same root path, but have different P4CLIENT / P4USER etc. settings configured - would need to have their own providers? Means that resolving the workspace to use involves checking which workspace a file belongs to as well

**Comment by mjcrouch** [comment]
Investigation into behaviour of perforce for .p4config vs other settings

* .p4config overrides environment variables
* .p4config at a lower level in the tree overrides .p4config at a higher level in the tree - one client can be nested in another client using .p4config files

Meanwhile in the extension, perforce.client etc. override everything, unless the workspace is not under the client root, in which case it will look for matching .p4config files

**Comment by mjcrouch** [comment]
Possible implementation - not sure if this covers all use cases, particularly if there are cases where we need a mix of settings from .vscode config and settings from the environment / enviro or .p4config files.

* Perforce.user/client/etc change from overriding to being defaults used when a perforce client is not found
* Start by scanning for a general p4 client at the root level of the workspace using p4 info, without the overriding user etc. 
   * If not found, try again with the overrides
* Always scan for P4CONFIG files
   * for each p4 config file found, run p4 info (without the overrides) in that directory
      * if not found, run with the overrides? (e.g. may be that only the user is required from the overrides and the client is not required)
* With the full set of p4 clients, create an scm provider for each one, which also knows the location of the root directory and all of the workspaces that are under it
* When running a command on a given file:
   * Look for the scm provider with the **most specific** root path for that file
      * e.g. looking at file /home/workspace/a/b/c/d.txt an scm provider for /home/workspace/a/b/ is more specific than one for /home/workspace/a
   * If one is found, we know now whether we need to override the user/client etc. with the config values, or if we can just run a p4 command without specifying the details (based on whether we needed to override when we found the initial instance)
    * If one is not found, this could be because the file is out of the workspace, or because the file is in the workspace but outside of a valid perforce client root.
      * If the file is out of the workspace. A couple of options (this could be switched in configuration)
          * Try the perforce command using the overridden values if specified
          * Try the perforce command without any overridden values and hope that the user has set up a .p4config or env variables that will allow it to work 
       * If the file is in the workspace but not in a client root, there isn't much chance that a bare p4 command will work because we would have found that in the first step of initialisation - just try with the overriden values?



This also assumes that to use .p4config files, you have a P4CONFIG configured - which is not currently required, as it *can* look for .p4config files use the values directly from it if no P4CONFIG is defined - however, this behaviour is technically incomplete compared to running p4, which will understand inheritance of config from parent directories. Overall it seems better to use perforce's own knowledge of clients instead of trying to reproduce it in the extension - but in some environments (remote development) it may not be easy to set the environment outside of vscode to tell it to look for .p4config files

**Comment by allender** [comment]
I feel like the current system is overly complicated.  Essentially we create a SCM provider for each workspace.  Workspace is defined as a 'folder' inside of vscode workspace config - and because of this, we get the multiple calls to the SCM provider for the same commands (see my [closed bug](https://github.com/mjcrouch/vscode-perforce/issues/62).  

It seems that by and large, we should let the user's environment decide all of this stuff.  Essentially, a user should do one of the following (in general):

* p4 port, client, user are defined in the environment (through p4 set or env variables).  Because they are in the environment, these are the default that get used unless the are overridden
* plugin can define the port, client, user to override what is defined in the project.  

That's it.  If the user wants to do something more obscure (such as client per folder or user per folder), they should use a p4config.  But perforce handles all this stuff internally with it's commands.  I'm not convinced that the plugin should do anything different.  If you run a p4 edit on a /a/b/c/file.txt perforce will either use the environment defaults or the proper p4config file that is used.  It will determine which p4config to use.  Granted, this does related to the CWD issue that was discussed earlier.  But setting the CWD to the folder where an operation is going to happen should guarantee that perforce will pick up the right p4 variables. 

It could very well be there are cases here that I don't fully understand.  I of course can not be sure of all usages of the plugin, but it also seems to be that simple is always better and that if there are special cases that need to be handled, it's better to either direct users to a more appropriate way of handlign those edge cases than making things more complicated in the code.  My 2 cents :)

**Comment by mjcrouch** [comment]
Yes... I've written a lot, but a lot of it is me waffling to myself, eventually I was coming to a similar conclusion that we should probably do something like you suggest, and not be overly flexible with settings.

At the core we have two problems to solve 
1. what is the set of scm providers to add to the scm panel?
2. exactly what command should I run for any given file

So, #1 still involves scanning the workspace to find out which workspaces could exist in the client, and coming to a set of unique possible client roots (instead of having many duplicate roots).
* If you have a multi-root workspace (i.e. multiple folders open in the same vscode workspace) then there could be a mix of manually defined settings per workspace and p4config etc in the other workspace.

I think the nuance is in that vscode has an inherently flexible heirarchy of settings and the combinations of settings, where you can define, for example just a user or just a client, or a user at one level and a client at another, which slightly contradicts the simple either/or approach, so it needs to be clear to a user what is happening when you set something in a particular place.

If they always override, then a user may get confusing results when they add a p4config and find it doesn't do what they expected, because at the user level they have a different P4CLIENT specified.

One thing I've wondered about is having a webview based interface to help the user set up the appropriate settings and diagnose issues

For #2, we need to know which file belongs to which client root, so we know whether we need to override the command line user / client etc, but that is not a particularly difficult task if we know the full set of client roots

**Comment by allender** [comment]
Right - these issues make sense.  I was thinking about this more, so here are my additional thoughts.   I'm trying to think about this from the perforce perspective.  And I want to make sure that we don't conflate the word "workspace" in the vscode and perforce sense.  They are two different meanings I think.  So I've been thinking of it from the perforce side and multiple vscode worksapces:

1.  there are multiple vscode workspaces that all belong to the same perforce workspace.  Those can all be controlled by a single SCM provider with a single set of p4port, p4user and p4client settings.  I think that by far this is the most common case.

2. There are multiple vscode workspaces that belong to different perforce workspaces.  This case is the most difficult one.  and I do think that this is not a common case, although I could certainly be wrong.

for 2), I'm wondering if the combination of the environment settings plus p4config would be enough to do the job.  (or just all p4config files).  it does get a tad complicated because operating on multiple files at the same time might be in different perforce workspaces.  There are a couple of ways to potentially solve this particular issue:

* run every file in one p4 command at a time. You can use the -d (or change the working directory) for the p4 command and the p4config should get picked up correctly (if there is one - otherwise the default settings are used).
* Put the files into buckets and run a p4 command per bucket (where a bucket is a specific set of perforce settings user/p4root/client). 
* Come up with a way for the user to define perforce settings per vscode workspace.

The problem with the buckets is that we'd have to parse out p4config files and figure out all that stuff, which is difficult and potentially fraught with bugs.  You did mention about coming up with UI to deal with settings per vscode workspace.   Maybe one of those is the right way to go about taking care of this particular issue.

Taking a step back though, taking care of what I think is the is common case of multiple vscode workspaces under the same perforce workspace, the code should be dead simple.  It's just an SCM provider for all workspaces.  Building on top of that makes sense to me and gets us to the point of just running a single p4 command per file in the directory where the file is and then you can rely on the p4config file get the right info to perforce.   There isn't extra information that is needed anywhere.  For sure, the code could be optimized (and potentially we could group files in the same folder into the same p4 command), but I'm just wondering if building more simply and then expanding will lead to less complication. 

I've been trying to figure out if there were specific issues that were brought up with regards to multiple vscode workspaces and (potentially) multiple perforce workspaces in this repo or the original, and I didn't see specific bugs so it's been admittedly difficult for me to understand what the potential edge cases are.

It could also be that per vscode workspace settings as an option is the way to go.  Maybe just being able to override the perforce settings for an individual workspace might be enough and be ok.

**Comment by jan11011977** [comment]
I agree setting the CWD to the folder where an operation is going to happen should guarantee that perforce will pick up the right p4 variables.

Another use case to consider is when a user opens a file in VSCode that isn't in the currently open folder. Any complex logic to do with scanning p4config files in the VSCode folder might fall down there. Running the command in the directory of the file will do the right thing.

**Comment by mjcrouch** [comment]
We do still need to know the possible client roots to be able to create the SCM providers for the sidebar

My latest thought is just to scan for p4config files to find where there *might* be potential clients, so that we can check if one exists and create an scm provider for it. Then consider the perforce.p4user etc. settings to **always be overrides** then instruct the user appropriately not to set them at the user level if they want to use p4configs.

When running commands, we could always run in the dir of the file even if we think we know the client, or we could use the client root if known (because we already created an scm provider for it), and the directory of the file otherwise. Things like 'revert changelist' from the scm view don't have a specific filename, so we have to just run these in the client root.

Generally I would prefer to consolidate down to single commands where possible, so if we ge a callback to say that 100 files have been deleted, we ideally don't want to run 100 delete commands - so we could implement something to segregate by directory. Having said that this is probably not a significant issue as there are very few cases where we explicitly operate on multiple files at once and they're mostly already one command per file.

**Comment by allender** [comment]
this multi-root thing is good and bad :(.  For things like our case, where we have a monolithic setup (i.e. 5 workspaces on the same depot), we are getting duplicated commands across all of those workspaces (which is what you are wanting to avoid by parsing out which workspace belongs where).  

For me, the pain point is that we run fstats, etc on the changelists, and that gets run multiple times (in my case) and it's expensive.  I know we talked about this on the delete action, but maybe running a command per file (in many cases) isn't a big deal.  add/revert/edit/delete.  I guess though that might be arguing for figuring out which vscode workspace belongs to what vscode workspace.  

Tricky problem.  i'll think more about it

**Comment by allender** [comment]
I saw your previous commit where you were working on this issue.  I had a thought.  Is it enough to run a p4 set at the root of each workspace to see if it's unique or not.  I mean, maybe it's all moot with your checkin that is going to close this issue, but was curious about this potential avenue.  Thanks for your work!

**Comment by mjcrouch** [comment]
that's effectively what it's doing, just with p4 info instead of p4 set
