### ISSUE TITLE
Implement 'Edit and Save' command

### ISSUE THREAD

**Issue by jan11011977** [mjcrouch/vscode-perforce#72]
**The Problem**
Right now 'edit on save' is implemented using the 'on save' callback. If this callback lasts longer than 700ms, Visual Studio Code will automatically cancel the callback and disable it. For people with slower Perforce servers, or Perforce servers that are further away, this makes 'edit on save' completely unusable.

NOTE: There used to be a setting to increase the timeout (editor.formatOnSaveTimeout) but this was removed.

**The Solution**
Implement a command which does a "p4 edit", and then triggers a VSCode 'Save File' command. Users could then rebind "ctrl+s" to this new command. This way we can have fully working 'edit on save' functionality, without timeouts.

For me and all my coworkers this elevate the plugins from 'almost useless' to 'awesome' :)

**Comment by mjcrouch** [comment]
That's an interesting idea!

Since I removed the bottleneck package and replaced it with my own implementation I've found that all perforce commands are quicker, but obviously that can't help with things like network latency, while this would resolve that.

The other thing to bear in mind is that not all save actions are a result of a manual user action - e.g. a find and replace will update and save files - so you will probably still want the setting enabled anyway for cases like that.

**Comment by allender** [comment]
right,  the 'open for edit' could fail so you will have to make sure that you don't fail to save on perforce error.  I do have a fundamental disagreement connecting vscode actions with perforce actions like this, but maybe it's something that's super useful.

I think that a longer term better architecture is not to run on events, but to collect on events, and then run a single (or multiple) command on the collected set soon after the event.  that eliminates the need to try and get around timers and also allows the extension to potentially collect multiple commands into a single p4 call

**Comment by mjcrouch** [comment]
> I think that a longer term better architecture is not to run on events, but to collect on events, and then run a single (or multiple) command on the collected set soon after the event. that eliminates the need to try and get around timers and also allows the extension to potentially collect multiple commands into a single p4 call

Generally yes, but I don't see how that's possible with running a p4 edit on file save, since the vscode API doesn't give us any other way to do that. The key problem being the writability of the file. Unless we were to manually make the file writable and _then_ run a p4 command on it - but that doesn't seem very nice from a perforce perspective

We do have edit on file edit, which could probably be batched up like that, so that kind of thing may make sense there, but generally you're only editing one file at a time so it probably wouldn't save many commands.

**Comment by jan11011977** [comment]
Right now, if the "open for edit" fails, it brings up the "overwrite" dialog box. For this feature, it could have the same behaviour.

Making the file writable is potentially dangerous: If the "p4 edit" fails or gets cancelled for some reason (maybe the user exits VSCode), then we are leaving the workspace in a corrupt state.

It's true that the "edit + save" idea wouldn't catch everything, but it would catch the 99% muscle-memory case of hitting CTRL+S. Right now I am hitting CTRL+S (which sometimes works), then when I see the 'overwrite' dialog I press "ALT+P, E" (p4 edit) and then I mash CTRL+S again repeatedly until the p4 edit has completed at which point CTRL+S completes successfully.

Having this reduced to a single CTRL+S which always works (possibly with a progress message so I know it's doing something) would be life changing, not just for me but for all my colleagues and presumably lots of people around the world who are wondering why CTRL+S often doesn't work.

**Comment by mjcrouch** [comment]
Published now!

I have tried to make it as robust as possible in terms of failed perforce commands - so if the command fails for any reason it will still try to save, though there is no timeout so if your perforce server takes 30 seconds to respond, your file may not be saved for 30 seconds.

Regardless, if you want to rebind ctrl+s, my recommendation would be to use the following keybindings - this way it will only switch on when you have a file that it will be able to open for edit - although there may be some edge cases, for example around trying to save very quickly after opening an editor

```
{
  "key": "ctrl+s",
  "command": "workbench.action.files.save",
  "when": "perforce.currentFile.status != 'NOT_OPEN'"
}
{
  "key": "ctrl+s",
  "command": "perforce.editAndSave",
  "when": "perforce.currentFile.status == 'NOT_OPEN'"
}
```

**Comment by jan11011977** [comment]
Thank you for implementing this! I'm giving it a try now. Seems to work

**Comment by jan11011977** [comment]
I have had 0 problems since setting this up. Thank you so much!
