### ISSUE TITLE
No source control present when opening only a file in vscode

### ISSUE THREAD

**Issue by allender** [mjcrouch/vscode-perforce#78]
**Describe the bug:**
Open clean VScode instance and open a file inside of a folder that is in a perforce workspace hierarchy.  The source control changelists and actions are not available.  If you open the folder then then are available.

**Expected behavior:**
Perforce actions should be available opening an individual file like they are with a folder

**To Reproduce:**
* Open new vscode instance
* Open a file that is inside the default perforce client
* source control operations/changelists are not available

**Versions & Details:**
 - Perforce extension:  3.10.0
 - VSCode version: 1.42.1
 - Operating System: Win10
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: NO

**Additional context**

<details>

```
Please open view -> Output, select "Perforce Log" from the dropdown and paste it here, if possible / relevant
```

</details>

**Comment by mjcrouch** [comment]
If you set activation mode to always, you should at least be able to perform the basic actions using the status bar, though you wouldn't see the scm provider view

I would probably describe this as an enhancement rather than a bug. Since we aren't being initialised with a vscode workspace - it would mean checking for every single file you open whether there is a workspace, then activating and de-activating the scm providers as you open and close each file. This is rather non-trivial and not really in the scope of the current expected behaviour.

I know the built-in git support is capable of this kind of thing, so it's definitely something to look at doing. We should at least implement #41 in such a way that it doesn't preclude this

**Comment by allender** [comment]
yeah, I agree with what you are saying.  Sorry, been a busy day for us for...reasons so I typed that up to quickly in between other things.

**Comment by mjcrouch** [comment]
no problem - I am having to spend a bit less time on this project atm, since our office is working from home now I can only spend so much time sitting in one place!

**Comment by allender** [comment]
we are in the same boat
